version: '3.3'
services:
  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    volumes:
      - /dockerodoo/volumes/postgresql/data:/var/lib/postgresql/data
      - /dockerodoo/volumes/postgresql/logs:/var/log      
      - /dockerodoo/volumes/postgresql/backups:/var/backups
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=strong_pg_odoo_password
    networks:
      postgres_subnet:
        ipv4_address: 172.19.0.2

  default:
    image: odoo:${TAG}
    command: start
    container_name: default
    restart: always
    ports:
      - 127.0.0.4:8069:8069
      - 127.0.0.4:8071:8071
      - 127.0.0.4:8072:8072
    depends_on:
      - postgres
    volumes:
      - /dockerodoo/volumes/opt/odoo/etc:/opt/odoo/etc
      - /dockerodoo/volumes/opt/odoo/custom:/opt/odoo/custom
      - /dockerodoo/volumes/opt/odoo/data/default:/opt/odoo/data
      - ./${TAG}/default/init:/opt/scripts
    environment:
      - CONF_FILE=/opt/odoo/etc/default.conf
      - ODOO_DB_HOST=172.19.0.2
      - ODOO_DB_PORT=5432
      - ODOO_ADDONS_PATH=/opt/odoo/custom,/opt/odoo/src/odoo/addons
      - ODOO_DB_NAME=dockerodoo-default
      - ODOO_DB_USER=odoo
      - ODOO_PROXY_MODE=True
      - ODOO_ADMIN_PASSWD=strong_odoo_master_password
      - ODOO_DB_PASSWORD=strong_pg_odoo_password
      - ODOO_DATA_DIR=/opt/odoo/data
      # - PYTHON_BIN=python3
      # - SERVICE_BIN=odoo-bin
      # - TARGET_UID=1000
    networks:
      postgres_subnet:
        ipv4_address: 172.19.0.4
    healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.4:8069/web"]
        interval: 30s
        timeout: 10s
        retries: 3


networks:
  postgres_subnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/24


